language: python

sudo: required

services:
  - docker

before_install:
  - cd docker && bash ./dockbuild.sh

script:
  - echo '#####' BUILDING AND RUNNING PYTHON TESTS && echo
  - bash ./testall python
  - echo && echo '#####' BUILDING (only) ANGULAR && echo
  - bash ./makedist angular
