language: python

sudo: required

services:
  - docker

before_install:
  - bash scripts/dhsetup.sh
  - cd docker && bash ./dockbuild.sh

script:
  - echo && echo '#####' BUILDING AND RUNNING PYTHON TESTS && echo
  - bash ./testall python
  - echo && echo '#####' BUILDING AND RUNNING JAVA TESTS && echo
  - bash ./makedist java
  - echo && echo '#####' BUILDING ANGULAR && echo
  - bash ./makedist angular
  - echo && echo '#####' RUNNING ANGULAR TESTS && echo
  - bash ./testall angular
